apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: '*'
    helm:
      valueFiles:
        - values.yaml
      values: |
        prometheus:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: ca-issuer
            hosts:
              - prometheus.kind.cluste
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
        grafana:
          enabled: true
          adminPassword: "admin"
          ingress:
            ingressClassName: nginx
            enabled: true
            path: /
            hosts:
              - grafana.kind.cluster
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 3
            externalUrl: "http://alertmanager.kind.cluster"
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        prometheusOperator:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
